name: "Terraform Plan Notification by Slack"
description: "Notify Terraform plan result to Slack"
branding:
  icon: "cloud"
  color: "purple"
inputs:
  plan-job-name:
    description: "Job name where `terraform plan` has been run"
    required: true
  plan-step-name:
    description: "Step name where `terraform plan` has been run"
    required: true
  workspace:
    description: "Workspace name"
  channel:
    description: "Slack Channel ID or name"
  github-token:
    description: "GitHub token"
  default-github-token:
    description: "Default gitHub token"
    default: ${{ github.token }}
  slack-bot-token:
    description: "Slack bot token"
  slack-webhook-url:
    description: "Slack webhook URL"
outputs:
  outside:
    description: "Changes outside section"
  action:
    description: "Resource actions section"
  output:
    description: "Output section"
  warning:
    description: "Warning section"
  summary:
    description: "Summary section"
  should-apply:
    description: "Should apply or not"
runs:
  using: "node16"
  main: "dist/index.js"
