name: "Terraform Plan Notification for PR"
description: "Add Terraform plan result as PR comment"
branding:
  icon: "cloud"
  color: "purple"
inputs:
  plan-job:
    description: "Job name where `terraform plan` has been run"
    required: true
  plan-step:
    description: "Step name where `terraform plan` has been run"
    required: true
  workspace:
    description: "Terraform workspace name"
  github-token:
    description: "GitHub token"
    default: ${{ github.token }}
outputs:
  outside:
    description: "Changes outside section"
  action:
    description: "Resource actions section"
  output:
    description: "Output section"
  warning:
    description: "Warning section"
  summary:
    description: "Summary section"
  should-apply:
    description: "Should apply or not"
runs:
  using: "node16"
  main: "dist/index.js"
